version: '3.8'

services:
  web:
    image: nginx:1.21-alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - tinyway_network
    restart: always

  redis:
    image: redis:6-alpine
    volumes:
      - ./redis.conf:/usr/local/etc/redis/redis.conf
      - redis_data:/var/lib/redis
    command: [ "redis-server", "/usr/local/etc/redis/redis.conf" ]
    networks:
      - redis_network
    restart: always

  tinyway:
    image: tinyway
    env_file:
      - .env
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - INDEX_REDIRECT_URL=https://stayforge.io
      - MAX_VALID_TIME=7776000
    networks:
      - redis_network
      - tinyway_network
    restart: always
    depends_on:
      - redis
      - web

volumes:
  redis_data:

networks:
  redis_network:
    internal: true
  tinyway_network:
    name: tinyway_network